export default {
    products:[
        {_id:'123',
        name: 'Slim-fit Suit',
        category:'Suits',
        brand:'Armani',
        image:'/images/suits/suit1.jpg',
        price: 4000,
        rating: 4.5,
        numReview:7},
        {_id:'133',
        name:'Regular-fit Suit',
        category:'Suits',
        brand:'Zara',
        image:'/images/suits/suit2.jpg',
        price: 200,
        rating: 3.9,
        numReview:10},
        {_id:'113',
        name:'Regular-fit Pants',
        category:'Pants',
        brand:'Zara',
        image:'/images/suits/pants1.jpg',
        price: 60,
        rating: 2.9,
        numReview:3},
        {_id:'1223',
        name:'Slim-fit Pants',
        category:'Pants',
        brand:'Zara',
        image:'/images/suits/pants2.jpg',
        price: 10,
        rating: 1.9,
        numReview:4},
        {_id:'1235',
        name:'Slim-fit Shirt',
        category:'Shirts',
        brand:'Zara',
        image:'/images/suits/shirt1.jpg',
        price: 60,
        rating: 3.9,
        numReview:16},
        {_id:'1237',
        name:'Regular-fit Shirt',
        category:'Shirts',
        brand:'Zara',
        image:'/images/suits/shirt2.jpg',
        price: 80,
        rating: 4.1,
        numReview:11}
    ]
}